php7fpm:
  build: php7
  volumes:
    - typo3:/var/www
  links:
    - mysql:mysql
php5fpm:
  build: php5
  volumes:
    - typo3:/var/www
  links:
    - mysql:mysql
hhvm:
  build: hhvm
  volumes:
    - typo3:/var/www
  links:
    - mysql:mysql
php7nginx:
  build: nginx
  volumes_from: [php7fpm]
  volumes: ["typo3:/var/www"]
  ports: ["8000:80"]
php5nginx:
  build: nginx
  volumes_from: [php5fpm]
  volumes: ["typo3:/var/www"]
  ports: ["8001:80"]
hhvmnginx:
  build: nginx
  volumes_from: [hhvm]
  volumes: ["typo3:/var/www"]
  ports: ["8002:80"]
mysql:
  image: mariadb
  environment:
    MYSQL_USER: typo3
    MYSQL_PASSWORD: typo3
    MYSQL_DATABASE: typo3
    MYSQL_ROOT_PASSWORD: typo3
